### ISSUE TITLE
Weird behavior after install from IFS

### ISSUE THREAD

**Issue by info-git** [tom-writes-code/rpgle-repl#21]
Hello
I'm an extremely noobish IBMi dev (just started on that tech stack two months ago) and this project would be extremely useful for me if I could use it.
However, when I write even very simple lines of codes and hit F11, it displays the message `Module not created. F7 to check spool files, F17 to view generated source`:
![image](https://user-images.githubusercontent.com/66995712/164472451-4939164a-ec2c-4203-9ecb-87e0ac888afe.png)

If I remove line number 4 where I assign to the variable it runs fine but shows no output.

Checking the spool file for REPL_MOD I can see this: 

```sql
Membre source modifié le 21/04/22  15:42:55                                                                                     
5770ST1 V7R3M0 160422           Créer un objet RPG ILE SQL         REPL_SRC                    21/04/22 15:42:55          Page  
                                           MESSAGES DE DIAGNOSTIC                                                               
   98                        COALESCE(MAX(result_number),0)+1,                             000000                               
5770ST1 V7R3M0 160422           Créer un objet RPG ILE SQL         REPL_SRC                    21/04/22 15:42:55          Page  
                                            MESSAGES DE DIAGNOSTIC                        
 ID-MSG  GRAV ENREG   TEXTE                                                               
 SQL0104  30      98  Position 49 Elément syntaxique ,0 n'est pas correct.                
                      Eléments possibles : ) ,.                                           
                     Récapitulatif des messages                                           
 Total     Info   Avertissement      Erreur   Grave  Terminal                             
       1        0         0          0        1         0                                 
 Erreurs de gravité 30 trouvées dans le source                                            
   104 enregistrements source traités                                                     
                                * * * * *    F I N  D E  L I S T E    * * * * *           
```

(pardon my company's French) So it looks like some kind of syntax error on the SQL request occurs.

------------------

Now, I'm just throwing stuff into the wind here, but because I have no experience with this platform and I know that encoding of characters on IMBi is massively complex, I'm wondering if this might be due to my install method.

Thing is, my company's as400 is firewalled so I couldn't use the default method for install, I had to download the savefile, then I copied it into the IFS through `IBM Rational Developer for i`, and then I ran the following commands:

```
CPYFRMSTMF FROMSTMF('/home/me/RPGLEREPL.FILE')                      
TOMBR('/qsys.lib/qgpl.lib/RPGLEREPL.FILE') MBROPT(*REPLACE) CVTDTA(*NONE)
```
```
CRTLIB LIB(RPGREPL) TEXT('REPL tool for ILE RPG snippets')
```
```
RSTOBJ OBJ(*ALL) SAVLIB(REPLBOB) DEV(*SAVF) SAVF(QGPL/RPGLEREPL) ALWOBJDIF(*COMPATIBLE) RSTLIB(RPGREPL)
```
```
CHGCMD CMD(RPGREPL/REPL) PRDLIB(RPGREPL)
```

**Comment by tom-writes-code** [comment]
Huh, this is unusual. The RPG you have written definitely looks valid to me - I wonder if this is a character mapping issue?

Do you have access to run queries via `strsql`? I'd be interested as to whether this fails interactively too.

```
SELECT 1,                                     
       COALESCE(MAX(result_number),0)+1,               
       TRIM('V') || ' = ' ||                    
       ''''|| TRIM(CAST(:repl_i AS CHAR(1000))) || ''''
  FROM replrslt                                        
 WHERE session_id = (QSYS2.JOB_NAME)
```

**Comment by info-git** [comment]
Yes, looks like this is the exact same after I copy pasted it from your comment into the 5250 emulator
![image](https://user-images.githubusercontent.com/66995712/164478734-336cb802-ca73-4ab6-afa7-4ca7bbbb4832.png)

**Comment by info-git** [comment]
Noticed the cast argument change, tried again, same result:
![image](https://user-images.githubusercontent.com/66995712/164480553-9a45b6eb-78c2-4093-99ae-00af701da17a.png)

**Comment by info-git** [comment]
![image](https://user-images.githubusercontent.com/66995712/164482048-b658e039-89f2-4fe4-8a01-b931ed835fcf.png)
Ran this from qp2term, this should make it possible to check if the character encoding was destroyed during transfer:
```
  $                                                                                
> sha256sum RPGLEREPL.FILE                                                         
  a2367f9a2ab4c28c30144bad102e80447c77031780e0b9ff82d79e29fefae4df  RPGLEREPL.FILE 
  $                                                                                
```

**Comment by tom-writes-code** [comment]
Even if the character coding was messed up, that message from `strsql` suggests it doesn't like the comma - before it even manages to check for the existence of the table.

Are you able to run COALESCE statements at all? Something very simple, like:
```
VALUES (             
  COALESCE(NULL, 'x')
)                    
```
![image](https://user-images.githubusercontent.com/101675587/164485004-d8a78baa-d77e-4c71-b393-1d02ceb78340.png)

**Comment by info-git** [comment]
Yes, that works fine
![image](https://user-images.githubusercontent.com/66995712/164485260-e0d64dc2-a023-44e2-9470-2f5048b28df0.png)
![image](https://user-images.githubusercontent.com/66995712/164485300-b67cf70a-6d25-4f8d-a3ff-753330affd34.png)

**Comment by tom-writes-code** [comment]
Ah, I think I might have replicated it. Does this work?
```
SELECT 1,                                           
       COALESCE(MAX(result_number), 0)+1,           
       TRIM('V') || ' = ' ||                        
       ''''|| TRIM(CAST('yo' AS CHAR(1000))) || ''''
  FROM replrslt                                     
 WHERE session_id = (QSYS2.JOB_NAME)                
```

**Comment by info-git** [comment]
The syntax error has changed: 
![image](https://user-images.githubusercontent.com/66995712/164486742-124d5aba-6125-4ee6-86a0-9317394c766d.png)

**Comment by info-git** [comment]
Yes! Concat won!
![image](https://user-images.githubusercontent.com/66995712/164487941-81f9c3fc-42c5-42bd-ae5d-bf7d7ef50c89.png)
![image](https://user-images.githubusercontent.com/66995712/164487976-e26bca7c-1d0c-4dbc-b252-d5446deca8eb.png)

**Comment by tom-writes-code** [comment]
Excellent! Thanks for your patience in running all of those. I'll create a PR to make it a bit more European friendly and publish a new version

**Comment by tom-writes-code** [comment]
The new save file in release v1.1.0-beta should resolve this.

**Comment by info-git** [comment]
Hey Tom
Sorry for reopening this but I tried this morning the new save file and it looks like the problem remains.
I have nuked the library and reloaded it, and made sure the objects used have the correct timestamp from your release from last night too.
![image](https://user-images.githubusercontent.com/66995712/164626395-79b2f46b-4ad9-48c7-91f8-1f3a60397d87.png)
![image](https://user-images.githubusercontent.com/66995712/164626450-68887df0-4282-4f9e-af97-a1aa6c557278.png)

**Comment by tom-writes-code** [comment]
Hi, sorry, I created the save file without checking out the latest version of all the changes. I've replaced the binary on the release now, and checked now that the generated code does separate out the comma and the 0.

https://github.com/tom-writes-code/rpgle-repl/releases/tag/v1.1.0-beta

**Comment by info-git** [comment]
![image](https://user-images.githubusercontent.com/66995712/164674862-1105e40b-bd11-4ece-951c-2bbe8f7825f4.png)
Got this now, I'm not sure but I think one of the object was not included in the savefile.

**Comment by info-git** [comment]
Yeah, I checked with the first version I downloaded and the restore command used to restore 18 objects, not 17.

**Comment by tom-writes-code** [comment]
Sorry, I see the mistake, and I've triple checked this one!

I've updated the file on here again: https://github.com/tom-writes-code/rpgle-repl/releases/tag/v1.1.0-beta

**Comment by info-git** [comment]
Thank you so much! It looks like it works now, awesome!
![image](https://user-images.githubusercontent.com/66995712/164678939-a22e4e20-6781-4404-bcce-2c24069cf635.png)
